#pragma once

#define VENDOR_ID 0xFEED
#define PRODUCT_ID 0x6060
#define DEVICE_VER 0x0001

#define MANUFACTURER "scylla_mod"
#define PRODUCT "scylla_mod"

#define MATRIX_ROWS 12
#define MATRIX_COLS 8

#define DIODE_DIRECTION COL2ROW

#define MATRIX_COL_PINS { GP0, GP1, GP2, GP3, GP4, GP5, GP6, GP7 }
#define MATRIX_ROW_PINS { GP8, GP9, GP10, GP11, GP12, GP13 }

#define MATRIX_COL_PINS_RIGHT { GP0, GP1, GP2, GP3, GP4, GP5, GP6, GP7 }
#define MATRIX_ROW_PINS_RIGHT { GP8, GP9, GP10, GP11, GP12, GP13 }

#define MASTER_LEFT
#define SERIAL_USART_TX_PIN GP28

#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_WPM_ENABLE
#define SPLIT_MODS_ENABLE


#define TFT_CS_PIN  GP17
#define TFT_SCK_PIN GP18
#define SPI_MOSI_PIN GP19
#define TFT_DC_PIN  GP20
#define TFT_RST_PIN GP21


#define QUANTUM_PAINTER_DISPLAY_TIMEOUT 0
#define QUANTUM_PAINTER_TASK_THROTTLE 8

#define ENCODER_A_PINS { GP26 }
#define ENCODER_B_PINS { GP22 }
#define ENCODER_A_PINS_RIGHT { GP22 }
#define ENCODER_B_PINS_RIGHT { GP26 }
#define ENCODER_RESOLUTIONS { 4 }
#define ENCODER_RESOLUTIONS_RIGHT { 4 }

#define VIAL_KEYBOARD_UID {0xAC, 0x8B, 0x4E, 0x4D, 0x7E, 0xCB, 0xA8, 0xA6}

#define DYNAMIC_KEYMAP_MACRO_COUNT 32
#define VIAL_TAP_DANCE_ENTRIES 32
#define VIAL_COMBO_ENTRIES 32
#define VIAL_KEY_OVERRIDE_ENTRIES 32